<dec f='include/python2.7/pyerrors.h' l='188' type='PyObject * PyErr_SetFromErrnoWithFilename(PyObject * , const char * )'/>
<use f='opencv/modules/python/src2/cv2.cv.hpp' l='2631' u='c' c='_ZL13pycvLoadImageP7_objectS0_S0_'/>
<use f='opencv/modules/python/src2/cv2.cv.hpp' l='2658' u='c' c='_ZL14pycvLoadImageMP7_objectS0_S0_'/>
